#!/usr/bin/env python3
"""Generate offline definitions from the canonical glossary. No packages required."""
from pathlib import Path
from html.parser import HTMLParser
import json,sys
ROOT=Path(__file__).resolve().parents[1]
class Entries(HTMLParser):
    def __init__(self):
        super().__init__();self.data={};self.ident=None;self.field=None
    def handle_starttag(self,tag,attrs):
        a=dict(attrs)
        if tag=='article' and 'gloss' in a.get('class','').split():
            self.ident=a['id'];self.data[self.ident]={'title':'','plain':'','exact':''}
        if self.ident:
            if tag=='h2':self.field='title'
            if tag=='p':self.field=None if a.get('class')=='gloss-meta' else 'exact' if a.get('class')=='exact' else 'plain'
    def handle_data(self,text):
        if self.ident and self.field:self.data[self.ident][self.field]+=text
    def handle_endtag(self,tag):
        if tag in ('p','h2'):self.field=None
        if tag=='article':self.ident=None
parser=Entries();parser.feed((ROOT/'glossary.html').read_text())
for entry in parser.data.values():
    for key in entry:entry[key]=' '.join(entry[key].split())
output='/* Generated by scripts/build-glossary.py; edit glossary.html. */\nconst GLOSSARY = '+json.dumps(parser.data,ensure_ascii=False,indent=2).replace('</','<\\/')+';\n'
target=ROOT/'assets/glossary-data.js'
if '--check' in sys.argv:
    assert target.read_text()==output,'Glossary definitions are stale: run python3 scripts/build-glossary.py'
    print(f'{len(parser.data)} glossary definitions are current.')
else:
    target.write_text(output);print(f'Generated {len(parser.data)} glossary definitions.')
